# Generated by Django 5.2.4 on 2025-08-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='original_short_video_file',
            field=models.FileField(blank=True, null=True, upload_to='shorts/originals/'),
        ),
    ]
